@startuml

title __BRIDGE's Class Diagram__\n

  namespace in.ashwanik.pdp.bridge {
    class in.ashwanik.pdp.bridge.BaseEntity {
        - createdTime : LocalDateTime
        - id : long
        - modifiedTime : LocalDateTime
        + getCreatedTime()
        + getId()
        + getModifiedTime()
        + setCreatedTime()
        + setId()
        + setModifiedTime()
    }
  }
  

  namespace in.ashwanik.pdp.bridge {
    class in.ashwanik.pdp.bridge.Customer {
        - email : String
        - firstName : String
        - lastName : String
        + getEmail()
        + getFirstName()
        + getLastName()
        + setEmail()
        + setFirstName()
        + setLastName()
    }
  }
  

  namespace in.ashwanik.pdp.bridge {
    interface in.ashwanik.pdp.bridge.CustomerRepository {
        {abstract} + create()
        {abstract} + get()
        {abstract} + update()
    }
  }
  

  namespace in.ashwanik.pdp.bridge {
    class in.ashwanik.pdp.bridge.CustomerRepositoryImpl {
        - customerDataProvider : DataProvider<Customer>
        + create()
        + get()
        + update()
        ~ CustomerRepositoryImpl()
    }
  }
  

  namespace in.ashwanik.pdp.bridge {
    interface in.ashwanik.pdp.bridge.DataProvider {
        {abstract} + create()
        {abstract} + get()
        {abstract} + update()
    }
  }
  

  namespace in.ashwanik.pdp.bridge {
    class in.ashwanik.pdp.bridge.MySqlProvider {
        + create()
        + get()
        + update()
    }
  }
  

  namespace in.ashwanik.pdp.bridge {
    class in.ashwanik.pdp.bridge.RedisProvider {
        + create()
        + get()
        + update()
    }
  }
  

  in.ashwanik.pdp.bridge.Customer -up-|> in.ashwanik.pdp.bridge.BaseEntity
  in.ashwanik.pdp.bridge.CustomerRepositoryImpl .up.|> in.ashwanik.pdp.bridge.CustomerRepository
  in.ashwanik.pdp.bridge.MySqlProvider .up.|> in.ashwanik.pdp.bridge.DataProvider
  in.ashwanik.pdp.bridge.RedisProvider .up.|> in.ashwanik.pdp.bridge.DataProvider


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
