@startuml

title __GITHUBJOBS's Class Diagram__\n

  namespace in.ashwanik.pdp.common.githubjobs {
    class in.ashwanik.pdp.common.githubjobs.BaseObject {
    }
  }
  

  namespace in.ashwanik.pdp.common.githubjobs {
    class in.ashwanik.pdp.common.githubjobs.GithubJob {
        - company : String
        - companyLogo : String
        - companyUrl : String
        - createdAt : String
        - description : String
        - howToApply : String
        - id : String
        - location : String
        - title : String
        - type : String
        - url : String
        + getCompany()
        + getCompanyLogo()
        + getCompanyUrl()
        + getCreatedAt()
        + getDescription()
        + getHowToApply()
        + getId()
        + getLocation()
        + getTitle()
        + getType()
        + getUrl()
        + setCompany()
        + setCompanyLogo()
        + setCompanyUrl()
        + setCreatedAt()
        + setDescription()
        + setHowToApply()
        + setId()
        + setLocation()
        + setTitle()
        + setType()
        + setUrl()
    }
  }
  

  namespace in.ashwanik.pdp.common.githubjobs {
    interface in.ashwanik.pdp.common.githubjobs.GithubJobClientContract {
        {abstract} + getJobs()
    }
  }
  

  namespace in.ashwanik.pdp.common.githubjobs {
    class in.ashwanik.pdp.common.githubjobs.GithubJobResponse {
    }
  }
  

  in.ashwanik.pdp.common.githubjobs.GithubJob -up-|> in.ashwanik.pdp.common.githubjobs.BaseObject


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
