@startuml

title __DEPENDENCY_INJECTION__\n

  namespace in.ashwanik.pdp.dependency_injection {
    class in.ashwanik.pdp.dependency_injection.App {
        + initialize()
    }
  }
  

  namespace in.ashwanik.pdp.dependency_injection {
    class in.ashwanik.pdp.dependency_injection.DbConnection {
        - connectionString : String
        - host : String
        + getConnectionString()
        + getHost()
        + setConnectionString()
        + setHost()
    }
  }
  

  namespace in.ashwanik.pdp.dependency_injection {
    class in.ashwanik.pdp.dependency_injection.FileDownloader {
        - okHttpClient : OkHttpClient
        + FileDownloader()
        + downloadFile()
        + getOkHttpClient()
    }
  }
  

  namespace in.ashwanik.pdp.dependency_injection {
    class in.ashwanik.pdp.dependency_injection.Injector {
        {static} - injector : Injector
        {static} + get()
        {static} + register()
    }
  }
  

  namespace in.ashwanik.pdp.dependency_injection {
    class in.ashwanik.pdp.dependency_injection.Linker {
        - registered : Map<Class<?>, Object>
        + register()
        + resolve()
    }
  }
  

  in.ashwanik.pdp.dependency_injection.Injector o-- in.ashwanik.pdp.dependency_injection.Linker : linker



@enduml
